/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AboutTeamDriveThemes {
    /// Deprecated - use driveThemes/backgroundImageLink instead.
    #[serde(rename = "backgroundImageLink", skip_serializing_if = "Option::is_none")]
    pub background_image_link: Option<String>,
    /// Deprecated - use driveThemes/colorRgb instead.
    #[serde(rename = "colorRgb", skip_serializing_if = "Option::is_none")]
    pub color_rgb: Option<String>,
    /// Deprecated - use driveThemes/id instead.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl AboutTeamDriveThemes {
    pub fn new() -> AboutTeamDriveThemes {
        AboutTeamDriveThemes {
            background_image_link: None,
            color_rgb: None,
            id: None,
        }
    }
}


