/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AboutDriveThemes {
    /// A link to this theme's background image.
    #[serde(rename = "backgroundImageLink", skip_serializing_if = "Option::is_none")]
    pub background_image_link: Option<String>,
    /// The color of this theme as an RGB hex string.
    #[serde(rename = "colorRgb", skip_serializing_if = "Option::is_none")]
    pub color_rgb: Option<String>,
    /// The ID of the theme.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl AboutDriveThemes {
    pub fn new() -> AboutDriveThemes {
        AboutDriveThemes {
            background_image_link: None,
            color_rgb: None,
            id: None,
        }
    }
}


