/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AboutStorageQuota : The user's storage quota limits and usage. All fields are measured in bytes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AboutStorageQuota {
    /// The usage limit, if applicable. This will not be present if the user has unlimited storage.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    /// The total usage across all services.
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<String>,
    /// The usage by all files in Google Drive.
    #[serde(rename = "usageInDrive", skip_serializing_if = "Option::is_none")]
    pub usage_in_drive: Option<String>,
    /// The usage by trashed files in Google Drive.
    #[serde(rename = "usageInDriveTrash", skip_serializing_if = "Option::is_none")]
    pub usage_in_drive_trash: Option<String>,
}

impl AboutStorageQuota {
    /// The user's storage quota limits and usage. All fields are measured in bytes.
    pub fn new() -> AboutStorageQuota {
        AboutStorageQuota {
            limit: None,
            usage: None,
            usage_in_drive: None,
            usage_in_drive_trash: None,
        }
    }
}


