/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommentQuotedFileContent : The file content to which the comment refers, typically within the anchor region. For a text file, for example, this would be the text at the location of the comment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommentQuotedFileContent {
    /// The MIME type of the quoted content.
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    /// The quoted content itself. This is interpreted as plain text if set through the API.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl CommentQuotedFileContent {
    /// The file content to which the comment refers, typically within the anchor region. For a text file, for example, this would be the text at the location of the comment.
    pub fn new() -> CommentQuotedFileContent {
        CommentQuotedFileContent {
            mime_type: None,
            value: None,
        }
    }
}


