/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DriveRestrictions : A set of restrictions that apply to this shared drive or items inside this shared drive.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DriveRestrictions {
    /// Whether administrative privileges on this shared drive are required to modify restrictions.
    #[serde(rename = "adminManagedRestrictions", skip_serializing_if = "Option::is_none")]
    pub admin_managed_restrictions: Option<bool>,
    /// Whether the options to copy, print, or download files inside this shared drive, should be disabled for readers and commenters. When this restriction is set to true, it will override the similarly named field to true for any file inside this shared drive.
    #[serde(rename = "copyRequiresWriterPermission", skip_serializing_if = "Option::is_none")]
    pub copy_requires_writer_permission: Option<bool>,
    /// Whether access to this shared drive and items inside this shared drive is restricted to users of the domain to which this shared drive belongs. This restriction may be overridden by other sharing policies controlled outside of this shared drive.
    #[serde(rename = "domainUsersOnly", skip_serializing_if = "Option::is_none")]
    pub domain_users_only: Option<bool>,
    /// Whether access to items inside this shared drive is restricted to its members.
    #[serde(rename = "driveMembersOnly", skip_serializing_if = "Option::is_none")]
    pub drive_members_only: Option<bool>,
}

impl DriveRestrictions {
    /// A set of restrictions that apply to this shared drive or items inside this shared drive.
    pub fn new() -> DriveRestrictions {
        DriveRestrictions {
            admin_managed_restrictions: None,
            copy_requires_writer_permission: None,
            domain_users_only: None,
            drive_members_only: None,
        }
    }
}


