/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileImageMediaMetadata : Additional metadata about image media, if available.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileImageMediaMetadata {
    /// The aperture used to create the photo (f-number).
    #[serde(rename = "aperture", skip_serializing_if = "Option::is_none")]
    pub aperture: Option<f32>,
    /// The make of the camera used to create the photo.
    #[serde(rename = "cameraMake", skip_serializing_if = "Option::is_none")]
    pub camera_make: Option<String>,
    /// The model of the camera used to create the photo.
    #[serde(rename = "cameraModel", skip_serializing_if = "Option::is_none")]
    pub camera_model: Option<String>,
    /// The color space of the photo.
    #[serde(rename = "colorSpace", skip_serializing_if = "Option::is_none")]
    pub color_space: Option<String>,
    /// The exposure bias of the photo (APEX value).
    #[serde(rename = "exposureBias", skip_serializing_if = "Option::is_none")]
    pub exposure_bias: Option<f32>,
    /// The exposure mode used to create the photo.
    #[serde(rename = "exposureMode", skip_serializing_if = "Option::is_none")]
    pub exposure_mode: Option<String>,
    /// The length of the exposure, in seconds.
    #[serde(rename = "exposureTime", skip_serializing_if = "Option::is_none")]
    pub exposure_time: Option<f32>,
    /// Whether a flash was used to create the photo.
    #[serde(rename = "flashUsed", skip_serializing_if = "Option::is_none")]
    pub flash_used: Option<bool>,
    /// The focal length used to create the photo, in millimeters.
    #[serde(rename = "focalLength", skip_serializing_if = "Option::is_none")]
    pub focal_length: Option<f32>,
    /// The height of the image in pixels.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// The ISO speed used to create the photo.
    #[serde(rename = "isoSpeed", skip_serializing_if = "Option::is_none")]
    pub iso_speed: Option<i32>,
    /// The lens used to create the photo.
    #[serde(rename = "lens", skip_serializing_if = "Option::is_none")]
    pub lens: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Box<crate::models::FileImageMediaMetadataLocation>>,
    /// The smallest f-number of the lens at the focal length used to create the photo (APEX value).
    #[serde(rename = "maxApertureValue", skip_serializing_if = "Option::is_none")]
    pub max_aperture_value: Option<f32>,
    /// The metering mode used to create the photo.
    #[serde(rename = "meteringMode", skip_serializing_if = "Option::is_none")]
    pub metering_mode: Option<String>,
    /// The number of clockwise 90 degree rotations applied from the image's original orientation.
    #[serde(rename = "rotation", skip_serializing_if = "Option::is_none")]
    pub rotation: Option<i32>,
    /// The type of sensor used to create the photo.
    #[serde(rename = "sensor", skip_serializing_if = "Option::is_none")]
    pub sensor: Option<String>,
    /// The distance to the subject of the photo, in meters.
    #[serde(rename = "subjectDistance", skip_serializing_if = "Option::is_none")]
    pub subject_distance: Option<i32>,
    /// The date and time the photo was taken (EXIF DateTime).
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// The white balance mode used to create the photo.
    #[serde(rename = "whiteBalance", skip_serializing_if = "Option::is_none")]
    pub white_balance: Option<String>,
    /// The width of the image in pixels.
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl FileImageMediaMetadata {
    /// Additional metadata about image media, if available.
    pub fn new() -> FileImageMediaMetadata {
        FileImageMediaMetadata {
            aperture: None,
            camera_make: None,
            camera_model: None,
            color_space: None,
            exposure_bias: None,
            exposure_mode: None,
            exposure_time: None,
            flash_used: None,
            focal_length: None,
            height: None,
            iso_speed: None,
            lens: None,
            location: None,
            max_aperture_value: None,
            metering_mode: None,
            rotation: None,
            sensor: None,
            subject_distance: None,
            time: None,
            white_balance: None,
            width: None,
        }
    }
}


