/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileLinkShareMetadata : Contains details about the link URLs that clients are using to refer to this item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileLinkShareMetadata {
    /// Whether the file is eligible for security update.
    #[serde(rename = "securityUpdateEligible", skip_serializing_if = "Option::is_none")]
    pub security_update_eligible: Option<bool>,
    /// Whether the security update is enabled for this file.
    #[serde(rename = "securityUpdateEnabled", skip_serializing_if = "Option::is_none")]
    pub security_update_enabled: Option<bool>,
}

impl FileLinkShareMetadata {
    /// Contains details about the link URLs that clients are using to refer to this item.
    pub fn new() -> FileLinkShareMetadata {
        FileLinkShareMetadata {
            security_update_eligible: None,
            security_update_enabled: None,
        }
    }
}


