/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileVideoMediaMetadata : Additional metadata about video media. This may not be available immediately upon upload.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileVideoMediaMetadata {
    /// The duration of the video in milliseconds.
    #[serde(rename = "durationMillis", skip_serializing_if = "Option::is_none")]
    pub duration_millis: Option<String>,
    /// The height of the video in pixels.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// The width of the video in pixels.
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl FileVideoMediaMetadata {
    /// Additional metadata about video media. This may not be available immediately upon upload.
    pub fn new() -> FileVideoMediaMetadata {
        FileVideoMediaMetadata {
            duration_millis: None,
            height: None,
            width: None,
        }
    }
}


