/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileContentHints : Additional information about the content of the file. These fields are never populated in responses.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileContentHints {
    /// Text to be indexed for the file to improve fullText queries. This is limited to 128KB in length and may contain HTML elements.
    #[serde(rename = "indexableText", skip_serializing_if = "Option::is_none")]
    pub indexable_text: Option<String>,
    #[serde(rename = "thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<Box<crate::models::FileContentHintsThumbnail>>,
}

impl FileContentHints {
    /// Additional information about the content of the file. These fields are never populated in responses.
    pub fn new() -> FileContentHints {
        FileContentHints {
            indexable_text: None,
            thumbnail: None,
        }
    }
}


