/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileImageMediaMetadataLocation : Geographic location information stored in the image.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileImageMediaMetadataLocation {
    /// The altitude stored in the image.
    #[serde(rename = "altitude", skip_serializing_if = "Option::is_none")]
    pub altitude: Option<f64>,
    /// The latitude stored in the image.
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// The longitude stored in the image.
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
}

impl FileImageMediaMetadataLocation {
    /// Geographic location information stored in the image.
    pub fn new() -> FileImageMediaMetadataLocation {
        FileImageMediaMetadataLocation {
            altitude: None,
            latitude: None,
            longitude: None,
        }
    }
}


