/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GeneratedIds : A list of generated file IDs which can be provided in create requests.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GeneratedIds {
    /// The IDs generated for the requesting user in the specified space.
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
    /// Identifies what kind of resource this is. Value: the fixed string \"drive#generatedIds\".
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The type of file that can be created with these IDs.
    #[serde(rename = "space", skip_serializing_if = "Option::is_none")]
    pub space: Option<String>,
}

impl GeneratedIds {
    /// A list of generated file IDs which can be provided in create requests.
    pub fn new() -> GeneratedIds {
        GeneratedIds {
            ids: None,
            kind: None,
            space: None,
        }
    }
}


