/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReplyList : A list of replies to a comment on a file.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReplyList {
    /// Identifies what kind of resource this is. Value: the fixed string \"drive#replyList\".
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The page token for the next page of replies. This will be absent if the end of the replies list has been reached. If the token is rejected for any reason, it should be discarded, and pagination should be restarted from the first page of results.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// The list of replies. If nextPageToken is populated, then this list may be incomplete and an additional page of results should be fetched.
    #[serde(rename = "replies", skip_serializing_if = "Option::is_none")]
    pub replies: Option<Vec<crate::models::Reply>>,
}

impl ReplyList {
    /// A list of replies to a comment on a file.
    pub fn new() -> ReplyList {
        ReplyList {
            kind: None,
            next_page_token: None,
            replies: None,
        }
    }
}


