/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RevisionList : A list of revisions of a file.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RevisionList {
    /// Identifies what kind of resource this is. Value: the fixed string \"drive#revisionList\".
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The page token for the next page of revisions. This will be absent if the end of the revisions list has been reached. If the token is rejected for any reason, it should be discarded, and pagination should be restarted from the first page of results.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// The list of revisions. If nextPageToken is populated, then this list may be incomplete and an additional page of results should be fetched.
    #[serde(rename = "revisions", skip_serializing_if = "Option::is_none")]
    pub revisions: Option<Vec<crate::models::Revision>>,
}

impl RevisionList {
    /// A list of revisions of a file.
    pub fn new() -> RevisionList {
        RevisionList {
            kind: None,
            next_page_token: None,
            revisions: None,
        }
    }
}


