/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StartPageToken {
    /// Identifies what kind of resource this is. Value: the fixed string \"drive#startPageToken\".
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The starting page token for listing changes.
    #[serde(rename = "startPageToken", skip_serializing_if = "Option::is_none")]
    pub start_page_token: Option<String>,
}

impl StartPageToken {
    pub fn new() -> StartPageToken {
        StartPageToken {
            kind: None,
            start_page_token: None,
        }
    }
}


