/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TeamDriveList : A list of Team Drives.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamDriveList {
    /// Identifies what kind of resource this is. Value: the fixed string \"drive#teamDriveList\".
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The page token for the next page of Team Drives. This will be absent if the end of the Team Drives list has been reached. If the token is rejected for any reason, it should be discarded, and pagination should be restarted from the first page of results.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// The list of Team Drives. If nextPageToken is populated, then this list may be incomplete and an additional page of results should be fetched.
    #[serde(rename = "teamDrives", skip_serializing_if = "Option::is_none")]
    pub team_drives: Option<Vec<crate::models::TeamDrive>>,
}

impl TeamDriveList {
    /// A list of Team Drives.
    pub fn new() -> TeamDriveList {
        TeamDriveList {
            kind: None,
            next_page_token: None,
            team_drives: None,
        }
    }
}


