/*
 * Drive API
 *
 * Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
 *
 * The version of the OpenAPI document: v3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TeamDriveRestrictions : A set of restrictions that apply to this Team Drive or items inside this Team Drive.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TeamDriveRestrictions {
    /// Whether administrative privileges on this Team Drive are required to modify restrictions.
    #[serde(rename = "adminManagedRestrictions", skip_serializing_if = "Option::is_none")]
    pub admin_managed_restrictions: Option<bool>,
    /// Whether the options to copy, print, or download files inside this Team Drive, should be disabled for readers and commenters. When this restriction is set to true, it will override the similarly named field to true for any file inside this Team Drive.
    #[serde(rename = "copyRequiresWriterPermission", skip_serializing_if = "Option::is_none")]
    pub copy_requires_writer_permission: Option<bool>,
    /// Whether access to this Team Drive and items inside this Team Drive is restricted to users of the domain to which this Team Drive belongs. This restriction may be overridden by other sharing policies controlled outside of this Team Drive.
    #[serde(rename = "domainUsersOnly", skip_serializing_if = "Option::is_none")]
    pub domain_users_only: Option<bool>,
    /// Whether access to items inside this Team Drive is restricted to members of this Team Drive.
    #[serde(rename = "teamMembersOnly", skip_serializing_if = "Option::is_none")]
    pub team_members_only: Option<bool>,
}

impl TeamDriveRestrictions {
    /// A set of restrictions that apply to this Team Drive or items inside this Team Drive.
    pub fn new() -> TeamDriveRestrictions {
        TeamDriveRestrictions {
            admin_managed_restrictions: None,
            copy_requires_writer_permission: None,
            domain_users_only: None,
            team_members_only: None,
        }
    }
}


